---
  - name: Play to install webserver
    hosts: projectx_dev
    gather_facts: true
    become: true
    tasks:
     - name: Installing webserver on RHEL server
       ansible.builtin.yum:
         name:
           - nginx
           - vim
           - wget
         state: present
         update_cache: true
       when: ansible_facts.os_family == "RedHat"
     - name: Installing webserver on Debin server
       ansible.builtin.apt:
         name:
           - nginx
           - vim
           - wget
         state: present
         update_cache: true
       when: ansible_facts.os_family == "Debian" 
